### ISSUE TITLE
 file_put_contents(outputChunk): failed to open stream: Permission denied

### ISSUE THREAD

**Issue by dkg5510** [nick322/secure-spreadsheet#6]
file_put_contents(outputChunk): failed to open stream: Permission denied {"userId":1,"exception":"[object] (ErrorException(code: 0): 

ERROR: file_put_contents(outputChunk): failed to open stream: Permission denied {"userId":1,"exception":"[object] (ErrorException(code: 0): file_put_contents(outputChunk): failed to open stream: Permission denied at vendor/nick322/secure-spreadsheet/src/Encrypt.php:471)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/s...', 471, Array)
#1 /var/www/html/.../vendor/nick322/secure-spreadsheet/src/Encrypt.php(471): file_put_contents('outputChunk', '\\x8E\\xAD$\\xA5\\xA0\\x8Cdf\\xCB\\r\\x18)\\xEA\\x81\\x15...', 8).

**Comment by nick322** [comment]
Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.

PHP Version

Composer Version

Package Version

Bug description

Steps to reproduce

Relevant log output

**Comment by nick322** [comment]
@dkg5510 Because I don't know how to reproduce the problem.
I'm not sure if this (master [06541b1](https://github.com/nick322/secure-spreadsheet/commit/06541b145b422e9e438bae15dc700d25570ea862) ) version can help you.
This is to put all the files in the temporary folder, which may solve the permission problem...
Can you give me a try?
``composer require nick322/secure-spreadsheet:06541b1``

**Comment by nick322** [comment]
Try it with the latest version(1.0.8).
